// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuBxuh_yM-7UCIKBWFHGTHSqV0YUKXn3M',
    appId: '1:927181798647:web:ac4937e51d40593d26a7f2',
    messagingSenderId: '927181798647',
    projectId: 'talk-line-b2cf5',
    authDomain: 'talk-line-b2cf5.firebaseapp.com',
    storageBucket: 'talk-line-b2cf5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWiku22PryuMWedOylfXZg6weY5jaImYs',
    appId: '1:927181798647:android:00ad6a70abfa743d26a7f2',
    messagingSenderId: '927181798647',
    projectId: 'talk-line-b2cf5',
    storageBucket: 'talk-line-b2cf5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC43Ex7JckyXw-KVPXx3YpS4hR62Olnsio',
    appId: '1:927181798647:ios:dbf001e52409f3e926a7f2',
    messagingSenderId: '927181798647',
    projectId: 'talk-line-b2cf5',
    storageBucket: 'talk-line-b2cf5.firebasestorage.app',
    iosBundleId: 'com.example.talkLine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC43Ex7JckyXw-KVPXx3YpS4hR62Olnsio',
    appId: '1:927181798647:ios:dbf001e52409f3e926a7f2',
    messagingSenderId: '927181798647',
    projectId: 'talk-line-b2cf5',
    storageBucket: 'talk-line-b2cf5.firebasestorage.app',
    iosBundleId: 'com.example.talkLine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuBxuh_yM-7UCIKBWFHGTHSqV0YUKXn3M',
    appId: '1:927181798647:web:e80b9d60c062543926a7f2',
    messagingSenderId: '927181798647',
    projectId: 'talk-line-b2cf5',
    authDomain: 'talk-line-b2cf5.firebaseapp.com',
    storageBucket: 'talk-line-b2cf5.firebasestorage.app',
  );
}
